@ECHO OFF 
PUSHD %~DP0
SET CURDIR=%CD%
POPD

SET OSGEO4W_ROOT=%CURDIR%\OSGeo4W
SET PYTHONHOME=%CURDIR%\Python25

:: Initialise OSGEO4W
PATH=%PYTHONHOME%;%OSGEO4W_ROOT%\bin;%PATH%
FOR %%f IN ("%OSGEO4W_ROOT%\etc\ini\*.bat") DO CALL "%%f"
CALL "%OSGEO4W_ROOT%\bin\gdal16.bat"

:: Some vars
::PYTHONHOME needs to be reset after initialising OSGEO4W
SET PYTHONHOME=%CURDIR%\Python25
SET PYTHONPATH=%PYTHONHOME%\Lib\lib-tk;%PYTHONPATH%
SET PYTHONPATH=%PYTHONHOME%\Lib\site-packages\pywin32_system32;%PYTHONHOME%\Lib\site-packages\win32;%PYTHONHOME%\Lib\site-packages\win32\lib;%PYTHONHOME%\Lib\site-packages\pythonwin;%PYTHONPATH%
SET PYTHONPATH=%OSGEO4W_ROOT%\bin;%OSGEO4W_ROOT%\apps\gdal-16\pymod\osgeo;%PYTHONPATH%
SET PYTHONPATH=%CURDIR%\lib;%PYTHONPATH%
SET PYTHONCASEOK=1

SET GDAL_DATA=%CURDIR%\gdal_data
PATH=%GDAL_DRIVER_PATH%;%PYTHONHOME%;%PYTHONPATH%;%PATH%
