@ECHO OFF 
PUSHD %~DP0
SET CURDIR=%CD%
CD ..
SET PARDIR=%CD%
POPD

SET PYTHONHOME=%PARDIR%\Python25

SET GDAL_ROOT=%PARDIR%\OSGeo4W
SET GDAL_DATA=%PARDIR%\gdal_data
SET GEOTIFF_CSV=%GDAL_DATA%
SET GDAL_DRIVER_PATH=%GDAL_ROOT%\apps\gdal-16\bin\gdalplugins
SET PROJ_LIB=%GDAL_ROOT%\share\proj

SET PYTHONPATH=%PYTHONHOME%
SET PYTHONPATH=%PYTHONHOME%\Lib;%PYTHONPATH%
SET PYTHONPATH=%PYTHONHOME%\DLLs;%PYTHONPATH%
SET PYTHONPATH=%PYTHONHOME%\Lib\lib-tk
SET PYTHONPATH=%PYTHONHOME%\Lib\site-packages\pywin32_system32;%PYTHONHOME%\Lib\site-packages\win32;%PYTHONHOME%\Lib\site-packages\win32\lib;%PYTHONHOME%\Lib\site-packages\pythonwin;%PYTHONPATH%
SET PYTHONPATH=%GDAL_ROOT%\bin;%GDAL_ROOT%\apps\gdal-16\pymod;%PYTHONPATH%
SET PYTHONPATH=%CURDIR%\lib;%PYTHONPATH%

PATH=%WINDIR%;%WINDIR%\System32;
PATH=%GDAL_ROOT%\bin;%PATH%
PATH=%GDAL_ROOT%\apps\gdal-16\bin;%PATH%
PATH=%GDAL_DRIVER_PATH%;%PATH%
PATH=%PYTHONPATH%;%PATH%
PATH=%PYTHONHOME%;%PATH%
