world=[
    [r'/vsizip/GeographicDescription.zip/world_countries.shp','CNTRY_NAME']
]
continental=[
    [r'/vsizip/GeographicDescription.zip/states.shp','sta_code']
]
local=[
    [r'/vsizip/GeographicDescription.zip/drainage_1m.shp','nam'],
    [r'/vsizip/GeographicDescription.zip/gazeteer.shp','gaz_name'],
    [r'/vsizip/GeographicDescription.zip/islands_reefs.shp','name'],
    [r'/vsizip/GeographicDescription.zip/capad.shp','name'],
    [r'/vsizip/GeographicDescription.zip/ramsar.shp','name'],
    [r'/vsizip/GeographicDescription.zip/builtup250k.shp','name']
]
